export * from './IClientDTO';
export * from './ICombinationDTO';
export * from './ILoginDTO';
export * from './IPaymentDTO';
export * from './IProductDTO';
export * from './IProviderDTO';
export * from './IPurchaseDTO';
export * from './ISaleDTO';
export * from './IUserDTO';
