export enum RoutesEnum {
  LOGIN = '/login',
  DASHBOARD = '/dashboard',
  STOCK = '/stock',
  CASH_RECEIPTS = '/cash-receipts',
  CASH_OUTFLOWS = '/cash-outflows',
  USERS = '/users',
  USERS_CREATE = '/users/create',

  PRODUCTS = '/stock/products',
  PRODUCTS_CREATE = '/stock/products/create',
  CLIENTS = '/cash-receipts/clients',
  CLIENTS_CREATE = '/cash-receipts/clients/create',
  SALES = '/cash-receipts/sales',
  SALES_CREATE = '/cash-receipts/sales/create',
  SALE_DETAIL = '/cash-receipts/sales/detail',
  PROVIDERS = '/cash-outflows/providers',
  PROVIDERS_CREATE = '/cash-outflows/providers/create',
  PURCHASES = '/cash-outflows/purchases',
  PURCHASES_CREATE = '/cash-outflows/purchases/create',
  PAYMENTS = '/cash-receipts/payments',
  PAYMENTS_CREATE = '/cash-receipts/payments/create',
  COMBINATIONS = '/stock/combinations',
  COMBINATIONS_CREATE = '/stock/combinations/create',
  DAILY_CASH_CLOSING = '/cash-receipts/daily-cash-closing',
  ORDERS_ACTIVES = '/cash-receipts/orders-actives',
}
