export enum RoutesEnum {
  LOGIN = '/login',
  HOME = '/home',
  PRODUCT_COMBINATION = '/product-combination',
  CASH_RECEIPTS = '/cash-receipts',
  CASH_OUTFLOWS = '/cash-outflows',

  PRODUCTS = '/products',
  PRODUCTS_CREATE = '/products/create',
  CLIENTS = '/clients',
  CLIENTS_CREATE = '/clients/create',
  SALES = '/sales',
  SALES_CREATE = '/sales/create',
  PROVIDERS = '/providers',
  PROVIDERS_CREATE = '/providers/create',
  PURCHASES = '/purchases',
  PURCHASES_CREATE = '/purchases/create',
  USERS = '/users',
  USERS_CREATE = '/users/create',
  PAYMENTS = '/payments',
  PAYMENTS_CREATE = '/payments/create',
  COMBINATIONS = '/combinations',
  COMBINATIONS_CREATE = '/combinations/create',
  DAILY_CASH_CLOSING = '/daily-cash-closing',
  ACAIS_ACTIVES = '/acais-actives',
}
